---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by boge.
--- DateTime: 2020/9/24,0024 10:49
---


-- XML 2 TS

xmlTots_start_id = 1000
xmlTots_readXMLFile = "D:/WorkSpace/LayaBox/TypeScriptLib/assets/lib_str.xml"
xmlTots_writeXMLFile = xmlTots_readXMLFile
xmlTots_writeTsFile = "D:/WorkSpace/LayaBox/TypeScriptLib/GameLib/src/com/LibStr.ts"
--xmlTots_namespaceName = "coreLib"



